### PR TITLE
Ignore IntelliJ files and Maven target directory

### PR DESCRIPTION
**Pull request by henri-tremblay**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/jmh pull/23/head:pull/23`
`$ git checkout pull/23`

### CODE REVIEW

**Comment by henri-tremblay** [comment]
I am already a contributor. You can see my name on https://www.oracle.com/technical-resources/oracle-contributor-agreement.html. However, that was for the old mercurial repository.

**Review by shipilev — APPROVED** [review]
This looks fine.

**Pull request closed without merging**
