### PR TITLE
CODETOOLS-7902825: Generated BenchmarkList file should be sorted for reproducibility

### PR DESCRIPTION
**Pull request by shipilev**
As stated in the RFE, JMH should sort BenchmarkListEntries before writing them out. It is cleaner to do in `BenchmarkList` itself, as it allows unit testing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Change must be properly reviewed

### Issue
 * [CODETOOLS-7902825](https://bugs.openjdk.java.net/browse/CODETOOLS-7902825): Generated BenchmarkList file should be sorted for reproducibility

### Reviewers
 * [Claes Redestad](https://openjdk.java.net/census#redestad) (@cl4es - no project role)

### Download
`$ git fetch https://git.openjdk.java.net/jmh pull/19/head:pull/19`
`$ git checkout pull/19`

### CODE REVIEW

**Review by cl4es — APPROVED** [review]
Thanks for picking this up! Changes looks good to me.

**Comment by shipilev** [comment]
Thanks!

/integrate

**Comment by shipilev** [comment]
Ah, silly Census rules.

**Comment by cl4es** [comment]
Did you need a formal Reviewer pre-skara? If not it seems like a bug that you couldn't /integrate here.

**Comment by shipilev** [comment]
> Did you need a formal Reviewer pre-skara? If not it seems like a bug that you couldn't /integrate here.

Yeah, Skara wants the formal Committer in Code Tools project, see `.jcheck/conf`. But, since you are not a formal Committer in Code Tools, that does not count. And my own review does not count for my own PRs. So...

**Comment by cl4es** [comment]
Yeah, at least I don't need a formal role to create a PR. Still, I do think we'd all be better off if the Code Tools project was formally subsumed into the main JDK project, at least w.r.t. roles (keep the separate JBS project and distinct repositories..)

**Pull request merged**
