### PR TITLE
7903409: JMH: Add JMH Visualizer as a community project

### PR DESCRIPTION
**Pull request by lenguyenthanh**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [CODETOOLS-7903409](https://bugs.openjdk.org/browse/CODETOOLS-7903409): JMH: Add JMH Visualizer as a community project

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jmh pull/91/head:pull/91` \
`$ git checkout pull/91`

Update a local copy of the PR: \
`$ git checkout pull/91` \
`$ git pull https://git.openjdk.org/jmh pull/91/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 91`

View PR using the GUI difftool: \
`$ git pr show -t 91`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jmh/pull/91.diff">https://git.openjdk.org/jmh/pull/91.diff</a>

</details>

### CODE REVIEW

**Comment by plokhotnyuk** [comment]
@lenguyenthanh Please, add [JMH Visualizer](https://github.com/jzillmann/jmh-visualizer) too.

**Review by shipilev — APPROVED** [review]
This looks good, thanks.

**Pull request closed without merging**
