### PR TITLE
7903327: Refactor class 'GCProfiler.VMSupport'

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

This patch initializes the field `churn` in method `tryInitChurn` instead of in method `newListener` and the field `chrun` will be cleared when starting the profiler each time. But currently the `Multiset` doesn't have a method named `clear`, so I always create a new `HashMultiset` for it in method `startChurnProfile`.

And this patch only initializes the field `listener` one time and doesn't mark it as `null` when the profiler finished. It is a balance between time and space and I think it is better to save the time (instantiation time and GC time). And a new field `started` is introduced to mark whether the profiler has started.

Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [CODETOOLS-7903327](https://bugs.openjdk.org/browse/CODETOOLS-7903327): Refactor class 'GCProfiler.VMSupport'

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jmh pull/80/head:pull/80` \
`$ git checkout pull/80`

Update a local copy of the PR: \
`$ git checkout pull/80` \
`$ git pull https://git.openjdk.org/jmh pull/80/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 80`

View PR using the GUI difftool: \
`$ git pr show -t 80`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jmh/pull/80.diff">https://git.openjdk.org/jmh/pull/80.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
Looks fine, but feel free to introduce `HashMultiset.clear()` (probably in `Multiset` interface) to save more memory on start.

**Comment by lgxbslgx** [comment]
> Looks fine, but feel free to introduce `HashMultiset.clear()` (probably in `Multiset` interface) to save more memory on start.

It is not good to complete it in this patch. Filed https://bugs.openjdk.org/browse/CODETOOLS-7903328 to follow up.

**Review by shipilev — APPROVED** [review]
Ok, fine.

**Comment by lgxbslgx** [comment]
Thanks for the review.

/integrate

**Pull request closed without merging**
