### PR TITLE
Add archetype version to the generate command

### PR DESCRIPTION
**Pull request by sabi0**
Without the explicit version the command generates a project using ancient JMH 0.7 version.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jmh.git pull/119/head:pull/119` \
`$ git checkout pull/119`

Update a local copy of the PR: \
`$ git checkout pull/119` \
`$ git pull https://git.openjdk.org/jmh.git pull/119/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 119`

View PR using the GUI difftool: \
`$ git pr show -t 119`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jmh/pull/119.diff">https://git.openjdk.org/jmh/pull/119.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Weird, I just tried to bootstrap with current command line, and it bootstrapped 1.37.  Check that your Maven indexes are correct.

```
$ mvn archetype:generate \
  -DinteractiveMode=false \
  -DarchetypeGroupId=org.openjdk.jmh \
  -DarchetypeArtifactId=jmh-java-benchmark-archetype \
  -DgroupId=org.sample \
  -DartifactId=test \
  -Dversion=1.0
...
[INFO] --- archetype:3.2.1:generate (default-cli) @ standalone-pom ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[INFO] Generating project in Batch mode
[INFO] Archetype [org.openjdk.jmh:jmh-java-benchmark-archetype:1.37] found in catalog remote
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: jmh-java-benchmark-archetype:1.37
[INFO] ----------------------------------------------------------------------------
...
```

The obvious downside of hard-coding the archetype version would be updating it every time JMH releases.

**Comment by sabi0** [comment]
It's weird. Running the command without the version multiple times gives me a next archetype version each time:
0.7 > 0.7.1 > 0.7.2 > 0.7.3 > 0.8 > 0.9 > 0.9.1

It might have something to do with our Nexus instance as I see the exact same set of versions there.
And after I deleted 0.9 and 0.9.1 from the local Maven repo I still got 0.9.2 on the next run.

There is version 1.37 in our Nexus too. But for some reason it is not being picked up.
However, running the command with `-DarchetypeVersion=LATEST` or `-DarchetypeVersion=RELEASE` consistently gives me the 1.37 version.

**Comment by sabi0** [comment]
Running with LATEST or RELEASE has this line in the log:
```
[INFO] Archetype repository not defined. Using the one from [org.openjdk.jmh:jmh-java-benchmark-archetype:0.9.3 -> http://prod.repo.internal.../nexus/content/groups/development] found in catalog remote
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: jmh-java-benchmark-archetype:RELEASE
```

Anyhow it appears `-DarchetypeVersion=RELEASE` solves the problem without bringing any additional maintenance.

**Comment by sabi0** [comment]
I am sorry for the offtopic. How do I get to submit a bug report for the JDK?

----------
**OS dynamic port range is not loaded on Windows**

Dynamic port range can be changed on Windows:
https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/default-dynamic-port-range-tcpip-chang
For instance, on my Windows 10 system it is configured as following:
```
C:\> netsh int ipv4 show dynamicport tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 1024
Number of Ports : 20977
```

But in JDK the range for Windows is hardcoded to 49152 - 65535:
https://github.com/openjdk/jdk/blob/master/src/java.base/windows/classes/sun/net/PortConfig.java

Because of that JVM does not recognize dynamically allocated by the OS port numbers as "ephemeral".
Resulting in particular in `SocketPermission "localhost:0", "accept,listen"` rejecting perfectly valid requests:
```
		SocketPermission policy = new SocketPermission("localhost:0", "accept,listen");
		SocketPermission request = new SocketPermission("localhost:20022", "accept");
		System.out.println(policy.implies(request));
		// prints "false"
```

Please implement loading of the OS dynamic port range on Windows, similar to how it is implemented for other OSes:
https://github.com/openjdk/jdk/blob/master/src/java.base/unix/classes/sun/net/PortConfig.java

**Pull request closed without merging**
