### PR TITLE
CODETOOLS-7903486: JMH: Revisit available jmh.executor options

### PR DESCRIPTION
**Pull request by shipilev**
We currently have a few executor options in JMH. As [CODETOOLS-7903476](https://bugs.openjdk.org/browse/CODETOOLS-7903476) shows, not all of them are ready to be used.

GitHub hits:
 "jmh.executor=CACHED_TPE", 0 hits
 "jmh.executor=FIXED_TPE", 0 hits
 "jmh.executor=VIRTUAL_TPE", 0 hits
 "jmh.executor=FJP", 3 hits (various forks of jsoniter)
 "jmh.executor=FJP_COMMON", 0 hits
 "jmh.executor=CUSTOM", 99 hits (various projects)

Looks like CACHED_TPE and FJP_COMMON can go away.
Others are renamed to capture their major characteristic.

Some light bikeshedding about the names is welcome.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [CODETOOLS-7903486](https://bugs.openjdk.org/browse/CODETOOLS-7903486): JMH: Revisit available jmh.executor options

### Reviewers
 * [Sergey Kuksenko](https://openjdk.org/census#skuksenko) (@kuksenko - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jmh.git pull/108/head:pull/108` \
`$ git checkout pull/108`

Update a local copy of the PR: \
`$ git checkout pull/108` \
`$ git pull https://git.openjdk.org/jmh.git pull/108/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 108`

View PR using the GUI difftool: \
`$ git pr show -t 108`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jmh/pull/108.diff">https://git.openjdk.org/jmh/pull/108.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jmh/pull/108#issuecomment-1573597835)

### CODE REVIEW

**Comment by shipilev** [comment]
@kuksenko, you might have an opinion here?

**Comment by kuksenko** [comment]
I agree. Using FJP_COMMON is dangerous, it's system-wide thread pool and its usage may give unpredictable behavior.
Also, I agree that CACHED is useless.
The current pair PLATFORM (was FIXED_TPE) and VIRTUAL and fine, I just realized that it makes sense to note in a comment that both executors provide threads that live through the whole benchmark execution.  (Especially that comment will be useful for VIRTUAL).
Now I am thinking if expanding the set of PLATFORM/VIRTUAL executors may be useful.
I am thinking about another pair platform/virtual when "Executors.newThreadPerTaskExecutor" is used. The pair will provide executors when every JMH iteration will use clean new threads.

**Comment by shipilev** [comment]
> I agree. Using FJP_COMMON is dangerous, it's system-wide thread pool and its usage may give unpredictable behavior. Also, I agree that CACHED is useless. The current pair PLATFORM (was FIXED_TPE) and VIRTUAL and fine, 

Please put a formal review on this PR then?

> I just realized that it makes sense to note in a comment that both executors provide threads that live through the whole benchmark execution. (Especially that comment will be useful for VIRTUAL). Now I am thinking if expanding the set of PLATFORM/VIRTUAL executors may be useful. I am thinking about another pair platform/virtual when "Executors.newThreadPerTaskExecutor" is used. The pair will provide executors when every JMH iteration will use clean new threads.

Maybe, and that would require a bit more reflection magic, which is not a problem. I would suggest waiting until we integrate #107 before adding more executor types.

**Review by kuksenko — APPROVED** [review]

**Comment by shipilev** [comment]
Thank you!

/integrate

**Pull request closed without merging**
